variable "env_type" {}
variable "owner" {}
variable "aws_region_az" {}
variable "aws_region" {}
variable "vpc_cidr_block" {}
variable "vpc_dns_support" {}
variable "vpc_dns_hostnames" {}
variable "map_public_ip_on_launch" {}
variable "rt_cidr_block" {}