variable "env_type" {} 
variable "owner" {}
variable "app_tag" {}
variable "aws_region_az" {}
variable "aws_region" {}
variable "instance_per_subnet" {}
variable "public_subnet" {}
variable vpc_id {}
variable vpc_cidr_block {}
variable "instance_ami" {}
variable "instance_type" {}
variable "key_pair" {}
variable "root_device_type" {}
variable "root_device_size" {}
variable "sg_ingress_proto" {}
variable "sg_ingress_ssh" {}
variable "sg_ingress_app" {}
variable "sg_ingress_http" {} 
variable "sg_egress_proto" {}
variable "sg_egress_all" {}
variable "sg_egress_cidr_block" {}