---
- hosts: all
  become: true
  tasks:

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker.io', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Restart docker service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: docker

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ app_tag }}"
        source: pull

    - name: Start App container
      docker_container:
        name: "springboot-application"
        image: "{{ app_tag }}"
        state: started
        output_logs: yes
        restart_policy: unless-stopped
        env:
          suchname: "{{ suchname }}"
        network_mode: "host"